WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE US_STATES (
    STATE_CODE CHAR(2) PRIMARY KEY,
    STATE_NAME VARCHAR2(64) NOT NULL,
    CAPITAL VARCHAR2(64) NOT NULL,
    REGION VARCHAR2(32) NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

